AWSTemplateFormatVersion: "2010-09-09"
Description: Accounting Service - Production

Mappings:
  Service:
    Env:
      Name: cf-accounting-service-example
      ShortName: accounting-service-example
      DNS: api.tinvio.com
      ECSCluster: production-services
      Port: 9099
      InternalNamespaceId: ns-eoeml76t253jeyvu  # internal.tinvio.com

Parameters:
  AppVersion:
    Type: String
    Description: App Version
  TasksCount:
    Type: Number
    Description: Num of Tasks
  ALBPriority:
    Type: Number
    Description: ALB Priority

Resources:
  
  ECSTaskDef:
    Type: AWS::ECS::TaskDefinition
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
    Properties: 
      NetworkMode: awsvpc
      Cpu: 512
      Memory: 1024
      ExecutionRoleArn: !Sub 'arn:aws:iam::${AWS::AccountId}:role/ecsTaskExecutionRole'
      TaskRoleArn: !Sub 'arn:aws:iam::${AWS::AccountId}:role/AccountingExampleServiceRole'
      Family: !FindInMap [Service, Env, Name]
      RequiresCompatibilities:
        - FARGATE
      Tags:
        - Key: AppVersion
          Value: !Ref AppVersion
      Volumes:
        - Name: tmp
        - Name: varlog
        - Name: filebeat
      ContainerDefinitions: 
        - Name: App
          Image: !Join
            - ''
            - - !Sub '${AWS::AccountId}.dkr.ecr.ap-southeast-1.amazonaws.com/accounting-service-example/app:'
              - !Ref AppVersion
          PortMappings: 
            - ContainerPort: !FindInMap [Service, Env, Port]
          Command: 
            - '-Xms128m'
            - '-Xmx1024m'
          Environment:
            - Name: AWS_EC2_METADATA_DISABLED
              Value: true
            - Name: APP_LOG_LEVEL
              Value: info
            - Name: DB_URL
              Value: tinvio-prod-db.tinvio.net
            - Name: DB_NAME
              Value: postgresproduction
            - Name: DB_RO_URL
              Value: tinvio-prod-ro-db.tinvio.net
            - Name: DB_POOL_IDLE_TIMEOUT
              Value: 60000
            - Name: DB_POOL_MAX_LIFETIME
              Value: 1800000
            - Name: DB_POOL_MAX_SIZE
              Value: 50
            - Name: DB_POOL_MIN_IDLE
              Value: 20
            - Name: DB_POOL_TIMEOUT
              Value: 60000
            - Name: PAYMENT_SERVICE_HOST
              Value: http://payments-service.internal.tinvio.com:9090
            - Name: SERVER_PORT
              Value: !FindInMap [Service, Env, Port]
          Secrets:
            - Name: DB_USERNAME
              ValueFrom: production.db.username
            - Name: DB_USER
              ValueFrom: production.db.username
            - Name: DB_PASSWORD
              ValueFrom: production.db.password
            - Name: DB_RO_USERNAME
              ValueFrom: production.db.ro.username
            - Name: DB_RO_PASSWORD
              ValueFrom: production.db.ro.password
            - Name: AUTH_SECRET
              ValueFrom: production.cas.auth_secret
          HealthCheck: 
            Command:
              - CMD-SHELL
              - 'ps | grep java | grep -v grep || exit 1'
            Interval: 30
            Timeout: 5
            StartPeriod: 30
            Retries: 3
          LogConfiguration: 
            LogDriver: awslogs
            Options: 
              awslogs-group: !Join
                - ''
                - - '/ecs/'
                  - !FindInMap [Service, Env, Name]
              awslogs-region: ap-southeast-1
              awslogs-stream-prefix: ecs
          MountPoints:
            - SourceVolume: tmp
              ContainerPath: /tmp
            - SourceVolume: varlog
              ContainerPath: /var/log
          ReadonlyRootFilesystem: true
        - Name: Filebeat
          Image: !Sub '${AWS::AccountId}.dkr.ecr.ap-southeast-1.amazonaws.com/accounting-service-example/filebeat:1'
          HealthCheck: 
            Command: 
              - CMD-SHELL
              - 'ps | grep filebeat | grep -v grep || exit 1'
            Interval: 30
            Timeout: 5
            StartPeriod: 30
            Retries: 3
          LogConfiguration: 
            LogDriver: awslogs
            Options:
              awslogs-group: !Join
                - ''
                - - '/ecs/'
                  - !FindInMap [Service, Env, Name]
              awslogs-region: ap-southeast-1
              awslogs-stream-prefix: ecs
          MountPoints:
            - SourceVolume: tmp
              ContainerPath: /tmp
            - SourceVolume: varlog
              ContainerPath: /var/log
            - SourceVolume: filebeat
              ContainerPath: /opt/filebeat/data
          ReadonlyRootFilesystem: true


  ECSService:
    Type: AWS::ECS::Service
    Properties: 
      Cluster: !FindInMap [Service, Env, ECSCluster]
      ServiceName: !FindInMap [Service, Env, ShortName]
      TaskDefinition: !Ref ECSTaskDef
      PlatformVersion: '1.4.0'
      DesiredCount: !Ref TasksCount
      HealthCheckGracePeriodSeconds: 300
      LoadBalancers: 
        - ContainerName: App
          ContainerPort: !FindInMap [Service, Env, Port]
          TargetGroupArn: !Ref ALBTargetGroup
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: DISABLED
          SecurityGroups:
            - sg-0850343d6d0751b15      # allow-prod-tasks
          Subnets:
            - subnet-077d4a0b99bd64294  # Private Subnet A
            - subnet-00df3ce0d9a027edf  # Private Subnet B
            - subnet-0d5fbd1e7b7a11889  # Private Subnet C
      DeploymentConfiguration: 
        DeploymentCircuitBreaker:
          Enable: Yes
          Rollback: Yes
        MaximumPercent: 200
        MinimumHealthyPercent: 100
      ServiceRegistries:
        - RegistryArn: !GetAtt ServiceDiscovery.Arn
    DependsOn:
      - ECSTaskDef
      - ECSLogGroup
      - ALBTargetGroup
      - ALBListener
      - ServiceDiscovery


  ALBTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties: 
      Name: !FindInMap [Service, Env, Name]
      VpcId: vpc-0309ecf52163f1b17    # main-production-network
      HealthCheckEnabled: true
      HealthCheckIntervalSeconds: 30
      HealthCheckPath: /actuator/health
      HealthCheckPort: traffic-port
      HealthCheckProtocol: HTTP
      HealthCheckTimeoutSeconds: 5
      HealthyThresholdCount: 3
      UnhealthyThresholdCount: 2
      Matcher: 
        HttpCode: 404
      Port: !FindInMap [Service, Env, Port]
      Protocol: HTTP
      TargetType: ip
      TargetGroupAttributes: 
        - Key: deregistration_delay.timeout_seconds
          Value: 60


  ECSLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Join
        - ''
        - - '/ecs/'
          - !FindInMap [Service, Env, Name]
      RetentionInDays: 30


  ALBListener:
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    Properties: 
      Actions: 
        - Type: forward
          TargetGroupArn: !Ref ALBTargetGroup
      Conditions: 
        - Field: host-header
          Values:
            - !FindInMap [Service, Env, DNS]
        - Field: path-pattern
          Values:
            - !Join
              - ''
              - - '/api/'
                - !FindInMap [Service, Env, ShortName]
                - '/*'
      ListenerArn: !Sub arn:aws:elasticloadbalancing:${AWS::Region}:${AWS::AccountId}:listener/app/collect-api-lb/b046b7fdb2d3c1c0/6442fa0651cc3bc6
      Priority: !Ref ALBPriority
    DependsOn:
      - ALBTargetGroup


  ServiceDiscovery:
    Type: AWS::ServiceDiscovery::Service
    Properties: 
      Name: !FindInMap [Service, Env, ShortName]
      NamespaceId: !FindInMap [Service, Env, InternalNamespaceId]
      Description: !FindInMap [Service, Env, Name]
      DnsConfig: 
        DnsRecords: 
          - Type: A
            TTL: 15
        RoutingPolicy: MULTIVALUE
      HealthCheckCustomConfig: 
          FailureThreshold: 1


Outputs:
  AppVersion:
    Description: App Version
    Value: !Ref AppVersion
  TaskCount:
    Description: Task Count
    Value: !Ref TasksCount
  AppUrl:
    Description: App URL
    Value: !Join
      - ''
      - - 'https://'
        - !FindInMap [Service, Env, DNS]
        - !Join
          - ''
          - - '/api/'
            - !FindInMap [Service, Env, ShortName]
            - '/*'