AWSTemplateFormatVersion: "2010-09-09"
Description: Accounting Service Example - Staging

Mappings:
  Service:
    Env:
      Name: cf-staging-accounting-service-example
      ShortName: accounting-service-example
      Port: 9099

Parameters:
  AppVersion:
    Type: String
    Description: App Version
  TasksCount:
    Type: Number
    Description: Num of Tasks
  ALBPriority:
    Type: Number
    Description: ALB Priority

Resources:
  
  ECSTaskDef:
    Type: AWS::ECS::TaskDefinition
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
    Properties: 
      NetworkMode: awsvpc
      Cpu: 512
      Memory: 1024
      ExecutionRoleArn: !Sub 'arn:aws:iam::${AWS::AccountId}:role/ecsTaskExecutionRole'
      TaskRoleArn: !Sub 'arn:aws:iam::${AWS::AccountId}:role/AccountingExampleServiceRole'
      Family: !FindInMap [Service, Env, Name]
      RequiresCompatibilities:
        - FARGATE
      Tags: 
        - Key: AppVersion
          Value: !Ref AppVersion
      Volumes: 
        - Name: tmp
        - Name: varlog
        - Name: filebeat
      ContainerDefinitions: 
        - Name: App
          Image: !Join
            - ''
            - - !Sub '${AWS::AccountId}.dkr.ecr.ap-southeast-1.amazonaws.com/accounting-service-example/app:'
              - !Ref AppVersion
          PortMappings: 
            - ContainerPort: !FindInMap [Service, Env, Port]
          Command: 
            - '-Xms128m'
            - '-Xmx1024m'
          Environment:
            - Name: AWS_EC2_METADATA_DISABLED
              Value: true
            - Name: APP_LOG_LEVEL
              Value: info
            - Name: DB_URL
              Value: db-nonprod.tinvio.dev
            - Name: DB_NAME
              Value: tinvioqa
            - Name: DB_USERNAME
              Value: tinvioqa
            - Name: DB_RO_URL
              Value: db-nonprod-ro.tinvio.dev
            - Name: DB_RO_USERNAME
              Value: ro_user
            - Name: DB_POOL_IDLE_TIMEOUT
              Value: 60000
            - Name: DB_POOL_MAX_LIFETIME
              Value: 1800000
            - Name: DB_POOL_MAX_SIZE
              Value: 50
            - Name: DB_POOL_MIN_IDLE
              Value: 20
            - Name: DB_POOL_TIMEOUT
              Value: 60000
            - Name: PAYMENT_SERVICE_HOST
              Value: http://payments-service.internal.tinvio.dev:9090
            - Name: SERVER_PORT
              Value: !FindInMap [Service, Env, Port]
          Secrets:
            - Name: DB_PASSWORD
              ValueFrom: qa.url-shortner.db_password
            - Name: DB_RO_PASSWORD
              ValueFrom: qa.collect_backend.db_ro_password
          HealthCheck: 
            Command:
              - CMD-SHELL
              - 'ps | grep java | grep -v grep || exit 1'
            Interval: 30
            Timeout: 5
            StartPeriod: 30
            Retries: 3
          LogConfiguration: 
            LogDriver: awslogs
            Options: 
              awslogs-group: !Join
                - ''
                - - '/ecs/'
                  - !FindInMap [Service, Env, Name]
              awslogs-region: ap-southeast-1
              awslogs-stream-prefix: ecs
          MountPoints:
            - SourceVolume: tmp
              ContainerPath: /tmp
            - SourceVolume: varlog
              ContainerPath: /var/log
          ReadonlyRootFilesystem: true
        - Name: Filebeat
          Image: !Sub '${AWS::AccountId}.dkr.ecr.ap-southeast-1.amazonaws.com/accounting-service-example/filebeat:1'
          HealthCheck: 
            Command: 
              - CMD-SHELL
              - 'ps | grep filebeat | grep -v grep || exit 1'
            Interval: 30
            Timeout: 5
            StartPeriod: 30
            Retries: 3
          LogConfiguration: 
            LogDriver: awslogs
            Options:
              awslogs-group: !Join
                - ''
                - - '/ecs/'
                  - !FindInMap [Service, Env, Name]
              awslogs-region: ap-southeast-1
              awslogs-stream-prefix: ecs
          MountPoints:
            - SourceVolume: tmp
              ContainerPath: /tmp
            - SourceVolume: varlog
              ContainerPath: /var/log
            - SourceVolume: filebeat
              ContainerPath: /opt/filebeat/data
          ReadonlyRootFilesystem: true


  ECSService:
    Type: AWS::ECS::Service
    Properties: 
      Cluster: collect-api-apps
      ServiceName: !FindInMap [Service, Env, ShortName]
      TaskDefinition: !Ref ECSTaskDef
      PlatformVersion: '1.4.0'
      DesiredCount: !Ref TasksCount
      HealthCheckGracePeriodSeconds: 300
      LoadBalancers: 
        - ContainerName: App
          ContainerPort: !FindInMap [Service, Env, Port]
          TargetGroupArn: !Ref ALBTargetGroup
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: DISABLED
          SecurityGroups:
            - sg-0136b06ccba15cc4b  # allow-qa-tasks
          Subnets:
            - subnet-00f6e463aa16d63b2  # Private Subnet A
            - subnet-0024ffc9fb9538d98  # Private Subnet B
            - subnet-0c070225df16be5a0  # Private Subnet C
      DeploymentConfiguration: 
        DeploymentCircuitBreaker:
          Enable: Yes
          Rollback: Yes
        MaximumPercent: 200
        MinimumHealthyPercent: 100
      ServiceRegistries:
        - RegistryArn: !GetAtt ServiceDiscovery.Arn
    DependsOn:
      - ECSTaskDef
      - ECSLogGroup
      - ALBTargetGroup
      - ALBListener
      - ServiceDiscovery


  ALBTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties: 
      Name: !FindInMap [Service, Env, Name]
      VpcId: vpc-08a527518a42d119a
      HealthCheckEnabled: true
      HealthCheckIntervalSeconds: 30
      HealthCheckPath: /actuator/health
      HealthCheckPort: traffic-port
      HealthCheckProtocol: HTTP
      HealthCheckTimeoutSeconds: 5
      HealthyThresholdCount: 3
      UnhealthyThresholdCount: 2
      Matcher: 
        HttpCode: 404
      Port: !FindInMap [Service, Env, Port]
      Protocol: HTTP
      TargetType: ip
      TargetGroupAttributes: 
        - Key: deregistration_delay.timeout_seconds
          Value: 60


  ECSLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Join
        - ''
        - - '/ecs/'
          - !FindInMap [Service, Env, Name]
      RetentionInDays: 30


  ALBListener:
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    Properties: 
      Actions: 
        - Type: forward
          TargetGroupArn: !Ref ALBTargetGroup
      Conditions: 
        - Field: path-pattern
          Values:
            - !Join
              - ''
              - - '/api/'
                - !FindInMap [Service, Env, ShortName]
                - '/*'
      ListenerArn: !Sub arn:aws:elasticloadbalancing:${AWS::Region}:${AWS::AccountId}:listener/app/collect-api-apps/468ee8605474b808/81ba666f085c8fa6
      Priority: !Ref ALBPriority
    DependsOn:
      - ALBTargetGroup


  ServiceDiscovery:
    Type: AWS::ServiceDiscovery::Service
    Properties: 
      Name: !FindInMap [Service, Env, ShortName]
      NamespaceId: ns-e6dz7u23na4nmd6p
      Description: !FindInMap [Service, Env, Name]
      DnsConfig: 
        DnsRecords: 
          - Type: A
            TTL: 15
        RoutingPolicy: MULTIVALUE
      HealthCheckCustomConfig: 
          FailureThreshold: 1


Outputs:
  AppVersion:
    Description: App Version
    Value: !Ref AppVersion
  TaskCount:
    Description: Task Count
    Value: !Ref TasksCount
  AppUrl:
    Description: App URL
    Value: !Join
      - ''
      - - 'https://api-staging.tinvio.dev'
        - !Join
          - ''
          - - '/api/'
            - !FindInMap [Service, Env, ShortName]
            - '/*'